### ISSUE TITLE
How to use log_ode? What does "window" represent time or number of points?

### ISSUE THREAD

**Issue by Krasner** [patrick-kidger/torchcde#25]
Hi Patrick,

First of all, thank you for posting this work - very impressive (and beyond my mathematical background).

I was able to use the neural CDE for a small dataset of irregularly sampled tracks, however when moving to a larger dataset the training times become much too long.

Therefore, I am attempting to use the RDE formulation with log signatures, but it's not clear to me how time is processed by logsig_windows function and what the window_length units are - time (seconds) or number of points.

Based on James Morrill's logsignature-example (https://github.com/jambo6/torchcde/blob/logsignature-example/example/logsignature_example.py) it looks like the window_length is in terms of number of points, but they how is time preserved?

In my application, I am presented with a data batch of size (b, num_points, C) where the time series are irregularly sampled so channel 0 is time - in hours, and channel 1-C are features. However, the time series can be of different length in terms of number of points and duration (hours).

x - is my data batch (filled forward so that there is the same # of points per track)
t = x[:,:,0] - time for each point in each track
y = torchcde.logsig_windows(x, depth=3, window=4)  - I don't pass in "t" explicitly it's already part of "x"
train_coeffs = torchcde.natural_cubic_coeffs(y)

Is this implementation correct? Does this mean that each signature window is looking at 4 sampled points? How does it represent the time variability from track to track: 4 points for track A can be 4 minutes, but for track B it can be 40 minutes, depending on the sampling rate.

Thanks,
Alex

**Comment by patrick-kidger** [comment]
Hi Alex,

The units of `window_length` is _integration time_, not data points. However, it turns out that in practice these two things should nearly always be the same thing. (See below.)

So your example code is correct. In what you've written, it is always 4 points, regardless of what times they correspond to. This is usually the desired behaviour. If you really want something different then you can use the `t` argument to `logsig_windows`. (Whose use might be clearer after the explanation below.)

_Aside: whether passing `t` like this will improve/decrease performance of a model, I don't know. In the theoretical limit they end up being the same thing -- i.e. the choice doesn't matter -- but I can completely believe that the numerical error in the differential equation solver will affect each case differently._

For completeness -- this is easily one of the most confusing aspects of working with neural CDEs. There are up to three different notions of time that may be considered:
- Observation times, i.e. the actual raw `t` in `the temperature had x=20 degrees value at time t=midday`. These should be appended to the data (`x` in your example) and then forgotten about. So what you're doing is correct in this regard.
- Integration time, which is the region of time integrated over in the solver. This is essentially an arbitrary choice, by reparameterisation invariance. Because it's arbitrary, it's an optional `t=None` argument for functions like `logsig_windows`, in which case it just defaults to an arithmetic sequence `0, 1, 2, ...`. So again what you're doing is correct in this regard. (And it is this that `window_size` is with respect to.) If I was making this library again I'd probably just remove these `t` options entirely to avoid the confusion, as they're used so little.
- Data points. That is, the `i` for counting your data `x_1, x_2, ... x_i, ...`. This is always just the values `0, 1, 2, ...`, so it will typically coincide with the integration time.

Does that make sense?

It's true that the documentation for `logsig_windows` (and for the above notions of time) could probably afford to be clearer. If you have any specific suggestions I'd be open to feedback / PRs.

**Comment by Krasner** [comment]
Thanks Patrick.

In that case, after applying logsig_windows I can use a fixed step solver with step size 1.0 correct?
`X = torchcde.NaturalCubicSpline(train_coeffs)`
`X0 = X.evaluate(X.interval[0])`
`z0 = self.initial(X0)`
`zT = torchcde.cdeint(X=X,z0=z0,func=self.func,t=X.interval,method='rk4',options=dict(step_size=1.0))`

Because the logsig will renormalize the observation times from raw data to just arithmetic sequence?

**Comment by patrick-kidger** [comment]
Actually, you can use `step_size=1.0` even without that. `NaturalCubicSpline` by default takes the integration time to be an arithmetic sequence.

I think you've got this now, but for the sake of any future readers:
- Generally the correct thing to do is to append observation times to your data, and thereafter forget about time altogether. (With the one exception of setting step sizes.)
- There's nothing special about NCDEs in that regard. You do the same when processing sequences with RNNs.
